name: venv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # or your target Python version
  - pip
  - absl-py=2.1.0
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - annotated-types=0.6.0
  - antlr-python-runtime=4.9.2
  - appdirs=1.4.4
  - asttokens=2.4.1
  - astunparse=1.6.3
  - async-timeout=4.0.3
  - attrs=23.2.0
  - autograd=1.6.2
  - autoray=0.6.9
  - beautifulsoup4=4.12.3
  - cachetools=5.3.3
  - certifi=2024.2.2
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - contourpy=1.2.1
  - cryptography=43.0.3
  - cycler=0.12.1
  - dask=2024.4.1
  - decorator=5.1.1
  - dulwich=0.22.3
  - einops=0.8.0
  - exceptiongroup=1.2.1
  - feedparser=6.0.11
  - filelock=3.14.0
  - fire=0.6.0
  - flatbuffers=24.3.25
  - fonttools=4.51.0
  - frozenlist=1.4.1
  - fsspec=2024.3.1
  - future=1.0.0
  - gast=0.5.4
  - google-pasta=0.2.0
  - grpcio=1.64.1
  - h5py=3.11.0
  - huggingface_hub=0.22.2
  - idna=3.7
  - ipykernel=6.29.4
  - ipython=8.18.1
  - ipywidgets=8.1.7
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.4.0
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.15
  - keras=3.3.3
  - kiwisolver=1.4.5
  - libclang=18.1.1
  - lightning=2.2.4
  - lightning-utilities=0.11.2
  - llvmlite=0.42.0
  - matplotlib=3.8.4
  - matplotlib-inline=0.1.7
  - ml-dtypes=0.3.2
  - mpmath=1.3.0
  - multidict=6.0.5
  - multipledispatch=1.0.0
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - numba=0.59.1
  - numpy=1.26.4
  - opt-einsum=3.3.0
  - packaging=24.0
  - pandas=2.2.2
  - parso=0.8.4
  - pillow=10.3.0
  - platformdirs=4.2.1
  - prompt-toolkit=3.0.43
  - protobuf=4.25.3
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure-eval=0.2.2
  - pycparser=2.22
  - pydantic=2.7.0
  - pygments=2.17.2
  - pyjwt=2.9.0
  - pyparsing=3.1.2
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.0.1
  - pytorch=2.3.0
  - torchvision=0.18.0
  - torchaudio=2.3.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - requests=2.31.0
  - rich=13.7.1
  - scikit-learn=1.4.2
  - scipy=1.13.0
  - seaborn=0.13.2
  - six=1.16.0
  - soupsieve=2.6
  - sympy=1.12
  - tabulate=0.9.0
  - tensorboard=2.16.2
  - termcolor=2.4.0
  - threadpoolctl=3.5.0
  - timm=0.9.16
  - toml=0.10.2
  - toolz=0.12.1
  - tornado=6.4
  - tqdm=4.66.2
  - traitlets=5.14.3
  - typing-extensions=4.11.0
  - tzdata=2024.1
  - urllib3=2.2.1
  - wcwidth=0.2.13
  - werkzeug=3.0.3
  - wrapt=1.16.0
  - yarl=1.9.4
  - zipp=3.18.1
  - pip:
      - asdfghjkl==0.1a2
      - backpack-for-pytorch==1.6.0
      - Deprecated==1.2.14
      - drawsvg==2.4.0
      - exqalibur==0.7.0
      - grimoirelab-toolkit==1.0.6
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - jaxtyping==0.2.28
      - kornia==0.7.2
      - kornia-rs==0.1.3
      - laplace-torch==0.1a2
      - lark-parser==0.12.0
      - latexcodec==3.0.0
      - linear-operator==0.5.2
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - namex==0.0.8
      - optree==0.11.0
      - partd==1.4.1
      - pennylane==0.35.1
      - pennylane-lightning==0.35.1
      - perceval==1.2.0
      - perceval-quandela==0.13.0
      - quantum-blackbird==0.5.0
      - quantum-xir==0.2.2
      - rustworkx==0.14.2
      - safetensors==0.4.3
      - semantic-version==2.10.0
      - sgmllib3k==1.0.0
      - stack-data==0.6.3
      - strawberryfields==0.23.0
      - tensorboard-data-server==0.7.2
      - thewalrus==0.21.0
      - torchmetrics==1.3.2
      - torchseg==0.0.1a4
      - typeguard==2.13.3
      - uncertainty-toolbox==0.1.1
      - unfoldNd==0.2.1
      - widgetsnbextension==4.0.14
      - xanadu-cloud-client==0.3.2

